config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "dashboard/index"
    get "login" => "sessions#new"
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
    get "dashboard" => "dashboard#index", as: :dashboard
    resources :tenants do
      collection do
        delete :delete_all, to: "tenants#delete_all", as: :delete_all
      end
      resources :sites do
        collection do
          delete :delete_all, to: "sites#delete_all", as: :delete_all
        end
        resources :nas do
          collection do
            delete :delete_all, to: "nas#delete_all", as: :delete_all
          end
        end
      end
      resources :clients do
        collection do
          delete :delete_all, to: "clients#delete_all", as: :delete_all
          post :import, to: "clients#import", as: :import
        end
      end
      resources :users do
        collection do
          delete :delete_all, to: "users#delete_all", as: :delete_all
        end
      end
    end
    resources :clients do
      resources :devices do
        collection do
          delete :delete_all, to: "devices#delete_all", as: :delete_all
        end
      end
    end
  end

  # RADIUS API endpoints for FreeRADIUS integration
  namespace :api do
    namespace :radius do
      post :authenticate
      post :authorize
      post :accounting
      get :status
      
      # NAS client management
      resources :clients, only: [:index, :create, :show, :update, :destroy] do
        member do
          post :test_connection
        end
      end
      post 'clients/generate_config', to: 'clients#generate_config'
      post 'clients/reload_freeradius', to: 'clients#reload_freeradius'
    end
  end

  put "/toggle_active", to: "toggle_active#update", as: :toggle_active

  get "/check_pnr", to: "pnumber#check_pnr", as: :check_pnr
  get "/check_phone", to: "pnumber#check_phone", as: :check_phone

  resource :session, only: [ :create, :update ]
  get "/guest/s/:site_name", to: "sessions#new", as: :new_session, constraints: { format: "html" }
  resolve("Session") { [ :session ] }
  get "otp", to: "sessions#otp", as: :otp
  get "success", to: "sessions#success", as: :success
  post "resend_otp", to: "sessions#resend", as: :resend_otp
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "admin/tenants#index"
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :client
  belongs_to :site, optional: true

  def self.authorized?(mac_address)
    device = find_by(mac_address: mac_address)
    return false if device.nil? || device.client.nil? || !device.client.active?
    return false if device.authentication_expire_at.nil? || device.authentication_expire_at < Time.current
    eu = External::Unifi::Base.new(site: device.site)
    return eu.is_mac_authorized?(mac_address) if eu
    false
  end

  def mac_address
    read_attribute(:mac_address).downcase.strip
  end

  def unifi_id
    read_attribute(:unifi_id).presence || mac_address.gsub(/:/, "")
  end

  def unauthorize
    if site.nil?
      return false
    end
    eu = External::Unifi::Base.new(site: site)
    load_client_info(eu)
    result = eu.revoke_guest_access(mac_address)
    result[:success] ?
      { success: true } :
      result
  end

  def authorize
    if site.nil? || !client.active?
      return false
    end
    eu = External::Unifi::Base.new(site: site)
    Rails.logger.error("Authorizing device with MAC address: #{mac_address} for site: #{site.name} using eu: #{eu.inspect}")
    if eu
      load_client_info(eu)
      result = eu.authorize_guest_access(
        mac_address: mac_address,
        minutes: time_limit,
        up: client.guest_tx,
        down: client.guest_rx,
        megabytes: client.guest_max
      )
      # result = eu.authorize_guest(
      #   url: site.controller_url,
      #   site_id: site.unifi_id,
      #   client_id: unifi_id,
      #   api_key: site.api_key,
      #   time: time_limit,
      #   guest_max: client.guest_max,
      #   guest_rx: client.guest_rx,
      #   guest_tx: client.guest_tx
      # )
      result[:success] ?
        update_client_info(eu, result) :
        result
    end
  end

  def time_limit
    val = authentication_expire_at || created_at
    val > 24.hours.from_now ? 1000000 : 1440
  end

  def load_client_info(eu)
    site_info = eu.site_info
    site.update(unifi_id: eu.get_id) if site_info
    unifi_client_id = eu.get_client_id(mac_address)
    unless unifi_client_id.nil?
      update unifi_id: unifi_client_id
    else
      guests = eu.list_guests.filter { |g| g["mac"] == mac_address }
      if guests.any?
        guests.each do |guest|
          update unifi_id: guest["id"] if guest["id"].present?
        end
        true
      else
        Rails.logger.error("ERROR: Unifi client info not found for MAC address: #{mac_address}")
        false
      end
    end
  end

  def update_client_info(eu, result)
    Rails.logger.error("Updating device info for MAC address: #{mac_address} with result: #{result.inspect}")
    if result[:data].present?
      data = result[:data]
      update(
        last_ap: data["ap_mac"],
        unifi_id: data["_id"],
        last_authenticated_at: Time.current,
        authentication_expire_at: time_limit.minutes.from_now
      )
    else
      load_client_info(eu)
    end
    Rails.logger.error("Device info updated for MAC address: #{mac_address}")
    { success: true }
  end
end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < Admin::BaseController
  before_action :set_client
  before_action :current_tenant
  before_action :set_device, only: %i[ show edit update destroy ]

  # GET /devices or /devices.json
  def index
    @devices = @client.devices.all
    @devices = case_insensitive_match(@devices, [ :mac_address, :last_ap ])
  end

  # GET /devices/1 or /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = @client.devices.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices or /devices.json
  def create
    @device = @client.devices.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to admin_client_devices_path(@client), notice: "Device was successfully created." }
        format.json { render :show, status: :created, location: admin_client_devices_path(@client) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1 or /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to admin_client_devices_path(@client), notice: "Device was successfully updated." }
        format.json { render :show, status: :ok, location: admin_client_devices_path(@client) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1 or /devices/1.json
  def destroy
    if !@device.nil?
      @device.destroy!

      respond_to do |format|
        format.html { redirect_to admin_client_devices_path(@client), status: :see_other, notice: "Device was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  def delete_all
    @devices = @client.devices # current_user.superuser? ? Device.all : Device.where(tenant_id: current_user.tenant_id)
    case_insensitive_match(@devices, [ :mac_address, :last_ap ]).destroy_all

    respond_to do |format|
      format.html { redirect_to admin_client_devices_path(@client), status: :see_other, notice: "All devices were successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

    def set_client
      @client = Client.find(params.expect(:client_id)) rescue nil
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = @client.devices.find(params.expect(:id)) rescue nil
    end

    # Only allow a list of trusted parameters through.
    def device_params
      params.expect(device: [ :client_id, :last_ap, :mac_address, :site_id, :last_authenticated_at, :last_otp, :authentication_expire_at ])
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/admin/devices/_device.html.erb
<div id="<%= dom_id device %>" data-controller="device" data-action="click->device#show" data-device-id="<%= device.id %>" data-client-id="<%= device.client.id %>" class="cursor-pointer p-2 grid grid-cols-5 w-full rounded-sm bg-indigo-100 sm:w-auto my-2 gap-2 space-y-1 items-center">
  <div class="col-span-4 truncate">
    <%= device.mac_address %>
  </div>
  <div class="col-span-1">
    <%= device.authentication_expire_at %>
  </div>
</div>

app/views/admin/devices/_form.html.erb
<%= form_with(model: device, url: device.persisted? ? admin_client_device_path(device.client, device) : admin_client_devices_path(device.client), class: "contents") do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul class="list-disc ml-6">
        <% device.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :client_id, "Client: #{device.client.name}" %>
    <%= form.hidden_field :client_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": device.errors[:client_id].none?, "border-red-400 focus:outline-red-600": device.errors[:client_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :site_id, "Site: #{device&.site&.name}" %>
    <%= form.hidden_field :site_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": device.errors[:site_id].none?, "border-red-400 focus:outline-red-600": device.errors[:site_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :last_ap %>
    <%= form.text_field :last_ap, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": device.errors[:last_ap].none?, "border-red-400 focus:outline-red-600": device.errors[:last_ap].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :mac_address %>
    <%= form.text_field :mac_address, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": device.errors[:mac_address].none?, "border-red-400 focus:outline-red-600": device.errors[:mac_address].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :last_authenticated_at %>
    <%= form.datetime_field :last_authenticated_at, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": device.errors[:last_authenticated_at].none?, "border-red-400 focus:outline-red-600": device.errors[:last_authenticated_at].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :last_otp %>
    <%= form.text_field :last_otp, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": device.errors[:last_otp].none?, "border-red-400 focus:outline-red-600": device.errors[:last_otp].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :authentication_expire_at %>
    <%= form.datetime_field :authentication_expire_at, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": device.errors[:authentication_expire_at].none?, "border-red-400 focus:outline-red-600": device.errors[:authentication_expire_at].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "heimdall_save_button" %>
  </div>
<% end %>

app/views/admin/devices/_modal.html.erb
<dialog data-modal-target="dialog" class="rounded-md m-auto shadow-lg p-6 w-96 bg-white">
  <h2 class="text-lg font-semibold mb-4">Confirm deletion</h2>
  <p class="mb-4">Are you sure you want to delete this client?</p>
  <form id="delete-form" method="post">
    <%= hidden_field_tag :_method, :delete %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token  %>
    <div class="flex justify-end gap-3">
      <button type="button" data-action="click->modal#cancel" class="px-4 py-2 bg-gray-200 rounded">Cancel</button>
      <button type="submit" data-action="click->modal#confirm" class="px-4 py-2 bg-red-600 text-white rounded">Delete</button>
    </div>
  </form>
</dialog>

app/views/admin/devices/edit.html.erb
<% content_for :title, "Editing device" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing device</h1>

  <%= render "form", device: @device %>

  <%= link_to "Show this device", admin_client_device_path(@device.client, @device), class: "heimdall_button" %>
  <%= link_to "Back to devices", admin_client_devices_path(@device.client), class: "heimdall_button" %>
</div>

app/views/admin/devices/index.html.erb
<% content_for :title, "Devices" %>

<div class="w-full">

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-md inline-block" id="alert"><%= alert %></p>
  <% end %>


  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Devices</h1>
    <div data-controller="tooltip" class="relative cursor-pointer group focus-within:z-10">
      <button type="button" data-action="click->tooltip#toggle" class="w-full bg-blue-200 text-white px-4 py-2 rounded focus:outline-none focus:ring-1 focus:ring-blue-500 hover:bg-blue-300 transition-colors duration-200">
        <span class="sr-only">Open device actions</span>
        <svg class="text-slate-400" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
          <path d="M480-160q-33 0-56.5-23.5T400-240q0-33 23.5-56.5T480-320q33 0 56.5 23.5T560-240q0 33-23.5 56.5T480-160Zm0-240q-33 0-56.5-23.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 33-23.5 56.5T480-400Zm0-240q-33 0-56.5-23.5T400-720q0-33 23.5-56.5T480-800q33 0 56.5 23.5T560-720q0 33-23.5 56.5T480-640Z"/>
        </svg>
      </button>
      <div data-tooltip-target="tooltip" class="absolute top-5 right-2 p-2 flex flex-col space-x-2 space-y-1 bg-blue-50 rounded-sm shadow opacity-0 pointer-events-none transition
           group-hover:opacity-100 group-hover:pointer-events-auto
           group-focus-within:opacity-100 group-focus-within:pointer-events-auto">

        <%= link_to @client.name, admin_tenant_client_path(@client.tenant, @client), class: "w-full whitespace-nowrap rounded-md border-slate-500 border-1 px-3.5 py-2.5 hover:bg-slate-100 text-slate-500 block font-medium text-left" %>
        <%= link_to "New device", new_admin_client_device_path(@client), class: "w-full whitespace-nowrap rounded-md border-slate-500 border-1 px-3.5 py-2.5 hover:bg-slate-100 text-slate-500 block font-medium text-left" %>
        <%= button_to "Delete all", delete_all_admin_client_devices_path(@client), method: :delete, class: "w-full whitespace-nowrap rounded-md border-slate-500 border-1 px-3.5 py-2.5 hover:bg-slate-100 text-slate-500 block font-medium text-left" %>
      </div>
    </div>
  </div>


  <div id="devices" class="min-w-full divide-y divide-gray-200 space-y-1">
    <% if @devices.any? %>
      <div class="grid grid-cols-5 w-full sm:w-auto my-1 gap-2 space-y-1">
        <div class="col-span-4">
          <strong class="font-medium ">MAC address:</strong>
        </div>
        <div class="col-span-1">
          <strong class="font-medium">Expires:</strong>
        </div>
      </div>

      <% @devices.each do |device| %>
        <%= render device %>
      <% end %>
    <% else %>
      <p class="text-center my-10">No devices found.</p>
    <% end %>
  </div>

</div>

app/views/admin/devices/new.html.erb
<% content_for :title, "New device" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New device</h1>

  <%= render "form", device: @device %>

  <%= link_to "Back to devices", admin_client_devices_path(@device.client), class: "heimdall_button" %>
</div>

app/views/admin/devices/show.html.erb
<% content_for :title, "Showing device" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl"><%= @device.mac_address %></h1>

  <div id="devices" class="min-w-full divide-y divide-gray-200 space-y-5">
    <div id="<%= dom_id @device %>" class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 w-full sm:w-auto my-5 gap-2 space-y-5">
      <div class="col-span-1">
        <strong class="block font-medium mb-1">Site:</strong>
        <%= @device&.site&.name %>
      </div>
      <div class="col-span-1">
        <strong class="block font-medium mb-1">Client:</strong>
        <%= @device.client.name %>
      </div>
      <div class="col-span-1">
        <strong class="block font-medium mb-1">MAC Address:</strong>
        <%= @device.mac_address %>
      </div>
      <div class="col-span-1">
        <strong class="block font-medium mb-1">Last AP:</strong>
        <%= @device.last_ap %>
      </div>
      <div class="col-span-1">
        <strong class="block font-medium mb-1">Last OTP:</strong>
        <%= @device.last_otp %>
      </div>
      <div class="col-span-1">
        <strong class="block font-medium mb-1">Unifi ID:</strong>
        <%= @device.unifi_id %>
      </div>
      <div class="col-span-1">
        <strong class="block font-medium mb-1">Last authenticated at:</strong>
        <%= @device.last_authenticated_at %>
      </div>
      <div class="col-span-1">
        <strong class="block font-medium mb-1">Authentication Expire At:</strong>
        <%= @device.authentication_expire_at %>
      </div>
    </div>
  </div>

  <div class="md:flex gap-2">
    <%= link_to "Edit this device", edit_admin_client_device_path(@device.client, @device), class: "heimdall_button" %>
    <%= button_to "Delete", "#", method: :delete, data: {
          action: "click->modal#show",
          action_url: admin_client_device_path(@device.client, @device)
        },
        form: { data: { turbo: false } }, # prevent button_to from wrapping a real form
        class: "heimdall_delete_button" %>
    <%= link_to "Back to devices", admin_client_devices_path(@device.client), class: "heimdall_button" %>
  </div>
</div>